### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [kingrpaul/louis-hemon_maria-chapdelaine_w-h-blake#1]
General Changes:

- [x] Rerun `se typogrify .` and commit those changes.

- [x] You can remove the periods after roman numerals ([SEMOS 8.8.5.3](https://standardebooks.org/manual/1.6.4/single-page#8.8.5.3)).

- [x] Since the verse lines are in French, the language tags can be applied to the `<blockquote>` elements. See the example and CSS for formatting in [SEMOS 5.3.1.3](https://standardebooks.org/manual/1.6.4/single-page#5.3.1.3).

- [x] "Laliberte" --> "Laliberté"

- [x] "Edwige Legare" --> "Edwige Légaré"

Chapter 1:

- [x] You can move the language tag to the `<p epub:type="bridgehead">` and remove the `<i>` element.

- [x] The accent marks are missing in the first verse.

- [x] "Thadee Pesant" --> "Thadée Pesant"

Chapter 2:

- [x] You can put `<em>` elements around "Heulle! Heulle!" and "Hue! Dia! Harrie!" for italics.

- [x] "Harrie" --> "Harrié"

Chapter 4: 

- [x] "Aglae" --> "Aglaë"

Chapter 5:

- [x] "dame de coeur" --> "dame de cœur"

- [x] "Grand’Mere" --> "Grand’Mère"

Chapter 9:

- [x] The verses are missing accent marks and ligatures. 

- [x] Verses 1 and 3 are missing indents.

- [x] _Claire Fontaine_ is the name of a song. It needs to be italicized and given song semantics.

Chapter 14:

- [x] "Tit’Sebe" --> "Tit’Sèbe"

Chapter 15:

- [x] The paragraph on line 61 is missing accent marks and ligatures.

- [x] "Gaspe" --> "Gaspé"

SVGs:

- [x] The cover.svg and titlepage.svg are missing the accent mark in the author's name. Make sure to change the name in all capital letters and rerun `se build-images .`

**Comment by kingrpaul** [comment]
@EmmaSweeney: One concern about "rerun typogrify" in that one of the changes it makes is to remove instances of commas appearing before an emdash, which I restored manually after the prior typogrify to create agreement with the page scans. I don't see this in the SEMOS and want to be sure before taking these out. Can you confirm?

**Comment by EmmaSweeney** [comment]
Yes, let typogrify remove the commas before em dashes. This rule is in the Chicago Manual of Style.

**Comment by kingrpaul** [comment]
@EmmaSweeney This text in Ch- 9 produces a lint warning and searching does not produce a better answer. 
`<i epub:type="se:name.publication.song">Claire Fontaine</i>`
Ignore the warning or is there a correction? TIA.

**Comment by EmmaSweeney** [comment]
If that produces a lint error then you can ignore that issue.

**Comment by kingrpaul** [comment]
6e0bdaec70fd5cc7af853461a9a370a9b31fe42c
